### ISSUE TITLE
Two defects in the source codes

### ISSUE THREAD

**Issue by jianchao-li** [moskomule/l0.pytorch#1]
There are two places that seem to be problematic in `l0module.py`.

- `__init__`
```
def __init__(self, origin, loc_mean=0, loc_sdev=0.01, beta=2 / 3, gamma=-0.1,
```
It should be `beta = 2.0 / 3`.

- `_get_mask`
```
s = F.sigmoid((torch.log(u) + torch.log(1 - u) + self.loc) / self.temp)
```
According to equation (10) of the paper, it should be 
```
s = F.sigmoid((torch.log(u) - torch.log(1 - u) + self.loc) / self.temp)
```

**Comment by moskomule** [comment]
Hi, thank you for your advice. 

* `beta = 2.0 / 3`: I'm using Python3 so no problem.

* `torch.log(u) - torch.log...`: Thank you. In the notebook, I use `+`...
